name: Greet Everyone
on: [push]

jobs:
  build:
    name: Greeting
    runs-on: elastest/ci-docker-e2e
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - uses: actions/setup-node@v1
        with:
          node-version: '12.10'
      - run: npm install
      - run: npm run test